services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    container_name: partner-frontend
    ports:
      - "80:3007"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${API_URL}
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    container_name: partner-backend
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
      - PORT=3008
      - JWT_SECRET=${JWT_SECRET}
    restart: always
